//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CherednichenkoKursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reis()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int IdReis { get; set; }
        public int Number { get; set; }
        public int IdCityOtpr { get; set; }
        public int IdCityPrib { get; set; }
        public System.DateTime Otpravl { get; set; }
        public System.DateTime Pribit { get; set; }
        public decimal Prise { get; set; }
        public int KolichMest { get; set; }
        public int IdAirplane { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
